
all:
	moc -i gtk/gtk_button.h -o gtk/moc_gtk_button.h
	moc -i gtk/gtk_entry.h -o gtk/moc_gtk_entry.h
	moc -i gtk/gtk_combo.h -o gtk/moc_gtk_combo.h
	
clean:
	rm -f gtk/moc_gtk_button.h
	rm -f gtk/moc_gtk_entry.h
	rm -f gtk/moc_gtk_combo.h

distclean:
	rm -f gtk/moc_gtk_button.h
	rm -f gtk/moc_gtk_entry.h
	rm -f gtk/moc_gtk_combo.h

